# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-upload:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --f pom.xml
    - name: Populate Staging Directory
      run: mkdir staging && cp target/* staging
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cab302-major-project
        path: staging
